name: movie_client
description: The client responsible for accessing movies domain data.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  http_client:
    path: ../http_client
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  http: ^0.13.5
  json_serializable: ^6.5.3
  mocktail: ^0.3.0
  test: ^1.21.5
